### ISSUE TITLE
edition2021 features really necessary?

### ISSUE THREAD

**Issue by jk** [alilleybrinker/semver-explain#2]
Hi, I tried to install semver-explain according to the instructions in the readme. But it complains, that I should use a cargo nightly version. Since I'm not a rust developer I'm refraining from doing so. Are these edition2021 feature really necessary?

```
# cargo install semver-explain
    Updating crates.io index
  Downloaded semver-explain v0.2.1
error: failed to parse manifest at `/Users/jkohl/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-explain-0.2.1/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature

# cargo --version
cargo 1.52.0 (69767412a 2021-04-21)

# uname -a
Darwin Bargain.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64
```

**Comment by alilleybrinker** [comment]
It doesn’t require a nightly version, but it does require the current version of Rust. If you have Rustup you can run `rustup update stable` to get the latest. I’m also interested in producing pre-built binaries so people don’t have to build from source.

**Comment by alilleybrinker** [comment]
That said, I can double check if it’s actually using any 2021-specific features. If not I’ll move the edition back to 2018.

**Comment by jk** [comment]
I had

```
# rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)
``` 

installed. After upgrading via `rustup update stable` running cargo installed worked. Thanks.

**Comment by alilleybrinker** [comment]
Took a look at reducing the minimum supported Rust version, and 1.53 is the earliest that will compile the code without modification. So I’ve made that the new minimum and moved from the 2021 edition to the 2018 edition.

So now at least any compiler version more recent than June of this year will work.

https://github.com/alilleybrinker/semver-explain/commit/d66c0d02ba0393c150846f5dd19239bdf5146461
