### ISSUE TITLE
Inconsistent ranges for ^major.minor requirements

### ISSUE THREAD

**Issue by trentj** [alilleybrinker/semver-explain#4]
From the [Cargo book](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements), any caret requirement starting with `1.` should be compatible up to `<2.0.0`:
```
^1.2.3  :=  >=1.2.3, <2.0.0
^1.2    :=  >=1.2.0, <2.0.0
^1      :=  >=1.0.0, <2.0.0
```
But this is what I found:
```
$ semver-explain "^1.2.3"
>=1.2.3, <2.0.0
$ semver-explain "^1.2"
>=1.2.0, <1.3.0
$ semver-explain "^1"
>=1.0.0, <2.0.0
```
Only major.minor strings appear to have this problem.
```
$ semver-explain --version
semver-explain 0.2.1
```

**Comment by alilleybrinker** [comment]
Thanks for the report! This does look like a bug. I'll try to find some time to get it corrected soon, and will add these examples as test cases.
